package com.example.syl.mydaotest;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.syl.mydaotest.Weather;

import com.example.syl.mydaotest.WeatherDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weatherDaoConfig;

    private final WeatherDao weatherDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weatherDaoConfig = daoConfigMap.get(WeatherDao.class).clone();
        weatherDaoConfig.initIdentityScope(type);

        weatherDao = new WeatherDao(weatherDaoConfig, this);

        registerDao(Weather.class, weatherDao);
    }
    
    public void clear() {
        weatherDaoConfig.getIdentityScope().clear();
    }

    public WeatherDao getWeatherDao() {
        return weatherDao;
    }

}
